### ISSUE TITLE
Identificar funcionalidades clave y secciones de la website de BIT SOX

### ISSUE THREAD

**Issue by navStudy** [BIT-SOX/.github#3]
### Descripción:
Bienvenidos, @kharoldcanova & @Narmes, este es su primer ticket colaborativo, en el que trabajaran evaluando diferentes referenciales del proyecto de la website, para ello, se les pedira revisar un PDF de estructura múltiple, el cual ya tiene las múltiples secciones a revisar para que el entorno en BIT SOX sea lo suficientemente intuitivo, recuerden que en teoria el proyecto empezara a partir del dia sábado 22 de Junio del año 2024, pero se les da plazo a entregar esta documentación hasta las **_12:00 PM_** de dicho día, no deben preocuparse, la idea estructural esta planificada de un modo que puede les interese evaluar con @navStudy, más adelante, igual manera si desean tener una reunión con el pueden comunicarse con para agendar una reunión.

#### Actividades a realizar:

- [x] Realizar una revisión de secciones de la página de **Inicio** sugerida
- [x] Reconocer patrones que pueden servir a desarrollar dichos entornos
- [x] Encontrar muestras y patrones que deberían respetar las **API's** para este proyecto (Al ser Front debemos entender la importancia de lo que buscamos traer a vista para el usuario)
- [x] Sugieran algunos patrones o formas intuitivas para que el proyecto sea más dinámico.
- [x] Revisar las propuestas con el equipo el dia **Jueves 20 de Junio del 2024**, pasada la fecha pueden terminar las consultas con @navStudy 

#### Tener en cuenta lo siguiente:
- Pueden asimilar las secciones basada en alguna de las tecnologías a aplicar: [**Angular v.16; Boostrapt 5, Hugeicons,, Jest**]
- Pueden sugerir variaciones de integración para el apartado de contacto.
- Evaluar particiones y patrones para el entorno a desarrollar

#### Archivos Adjuntos
[PDF - Website y Diseño / Supervisado por el CTO ](https://drive.google.com/drive/folders/1WavrQpjzwUTz3KErKYGph05jamTQq0f3?usp=drive_link)

**Comment by kharoldcanova** [comment]
https://docs.google.com/document/d/1uNJaZx9g9qp-RpBoS9yLMoqBfEFtDa4xwiolIXI1DYo/edit
